# =============================================================================
# Modded Server
# =============================================================================
# Hostname: modded.local
# Type: FORGE
# =============================================================================

services:
  mc-modded:
    image: itzg/minecraft-server:java21
    container_name: mc-modded
    restart: "no"
    tty: true
    stdin_open: true
    env_file:
      - ../../.env
      - config.env
    environment:
      EULA: "TRUE"
    volumes:
      - ./data:/data
      - ./logs:/data/logs
      - ../../worlds:/worlds:rw
      - ../../shared/mods:/mods:ro
    networks:
      - minecraft-net
    labels:
      - "mc-router.host=modded.local"
      - "mc-router.auto-scale-up=true"
      - "mc-router.auto-scale-down=true"

